# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  box = "ubuntu/trusty64"

  config.vm.define :trusty do |trusty|
    trusty.vm.box = box
    trusty.vm.network "private_network", ip: "10.0.0.2"
    #trusty.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh", auto_correct: true
    trusty.vm.hostname = "zcfd-trusty"

    config.ssh.forward_agent = true
    config.vm.provider "virtualbox" do |v|
      v.memory = 8192
      v.cpus = 4
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//git", "1"]
    end

    ## load the salt folder
    trusty.vm.synced_folder "salt/roots/", "/srv/"
    trusty.vm.synced_folder "../scripts", "/srv/scripts"

    # provision
    trusty.vm.provision :salt do |salt|
      salt.minion_config = "salt/minion"
      salt.run_highstate = true
    end

  end

end

