# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  box = "chef/centos-6.5"

  config.vm.define :centos65 do |centos65|
    centos65.vm.box = box
    centos65.vm.network "private_network", ip: "10.0.0.2"
    #centos65.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh", auto_correct: true
    centos65.vm.hostname = "zcfd-centos65"

    config.vm.provider "virtualbox" do |v|  
      v.memory = 2048
      v.cpus = 1
    end
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"] 
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//git", "1"]  
    end

    ## load the salt folder
    centos65.vm.synced_folder "salt/roots/", "/srv/"
    centos65.vm.synced_folder "../scripts", "/srv/scripts"
    
    # provision
    centos65.vm.provision :salt do |salt|
      salt.minion_config = "salt/minion"
      salt.run_highstate = true
    end

  end
  
end

